FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache

COPY main.py ./

EXPOSE 8080

CMD ["uv", "run", "flask", "--app", "main", "run", "--host", "0.0.0.0", "--port", "8080"]