from typing import Protocol

class AgentTransport(Protocol):
    def initialize(self) -> str | None: ...
    def complete_auth(self, session_id: str) -> None: ...
    def send_prompt(self, prompt: str) -> str: ...
